### ISSUE TITLE
AttributeError: module 'jax.numpy' has no attribute 'DeviceArray'

### ISSUE THREAD

**Issue by ernestchu** [google-deepmind/jaxline#15]
In jax 0.4.14, jax.numpy.DeviceArrary is deprecated, see
https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-14-july-27-2023

The snippet below produces the error in the title when importing `jaxline.experiment`

https://github.com/deepmind/jaxline/blob/f1503f6a06d46aa9eb2eab8eed6130895148ffa2/jaxline/utils.py#L334-L339

https://github.com/deepmind/jaxline/blob/f1503f6a06d46aa9eb2eab8eed6130895148ffa2/jaxline/experiment.py#L49-L51

**Comment by danieldonnelly7** [comment]
Hi there, just want to add that I've also been encountering this issue.

**Comment by bhack** [comment]
Can we merge this?

**Comment by bhack** [comment]
I think we could close this

**Comment by ernestchu** [comment]
LGTM
